[package]
name = "bp_photos"
version = "0.3.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/changs/bp_photos"

[dependencies]
arboard = { version = "3.6", features = ["wayland-data-control"] }
bytemuck = { version = "1.25.2", features = ["derive"] }
dirs = "7.0.0"
eframe = { version = "0.36.2", default-features = false, features = ["wgpu", "default_fonts", "wayland", "x11", "persistence"] }
half = "2.7.1"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "tiff", "webp"] }
kamadak-exif = "0.6"
libheif-rs = "3"
pollster = "1.0.1"
quick-xml = "0.42.0"
rawler = "0.8.0"
rfd = "0.17.2"
ureq = "3"
wgpu = "30"
zip = { version = "2", default-features = false, features = ["deflate"] }
zune-core = "0.5"
zune-jpeg = "0.5"
